### ISSUE TITLE
Page width malfunction

### ISSUE THREAD

**Issue by IonRutz** [MachoThemes/decode#106] opened 2016-06-06 09:42 UTC
As soon as the browser window expands past the 68.5em screen width, all page content vanishes because of that bogus .site-main {width: 792% }. The inline css should be site-main {width: 79.2%}, so the problem is literally just a missing decimal point.

Thx

**Comment by cristianraiber** [comment] 2016-06-06 13:49
Duplicate of #96

**Closed by cristianraiber** 2016-06-06 13:49 UTC
