### ISSUE TITLE
Change the theme credits to 'Decode Theme by Scott Smith'

### ISSUE THREAD

**Issue by NicolasWeb** [MachoThemes/Decode#59] opened 2016-02-15 15:59 UTC
I thnik it's fair (and useful) to show the Theme and author names.
However, the actual output seems confusing to my readers.
Could the credits be changed from 'Decode by Scott Smith' to 'Decode Theme by Scoot Smith'

**Comment by cristianraiber** [comment] 2016-02-15 16:01
Hi @NicolasWeb,

I've added this to the list of enhancements for the 3.10 version. 

This fix will be included in our next update.

Thanks.

**Closed** 2016-02-18 11:47 UTC
Labels: enhancement

**Comment by cristianraiber** [comment] 2016-02-18 11:59
This is a duplicate of #71
